### ISSUE TITLE
Add package metadata to help pip install valid versions

### ISSUE THREAD

**Issue by NSGregory** [AllenCellModeling/aicspylibczi#107]
## System and Software
* aicspylibczi Version: Presumably 3.0.5
* Python Version: 3.6.9 - 64 bit
* Operating System: Ubuntu 18.04.4 LTS - 64 bit

## Description
*A clear description of the bug*
Fails to install.  Potentially related to the CMake List error from issue #90.

## Expected Behavior
*What did you expect to happen instead?*
Install

## Reproduction
*A minimal example that exhibits the behavior.*
pip3 install aicspylibczi
sudo pip3 install aicspylibczi

## Environment
*Any additional information about your environment*

## Error Log
WARNING: Ignoring invalid distribution -illow (/usr/local/lib/python3.6/dist-packages)
Installing collected packages: aicspylibczi, aicsimageio
    Running setup.py install for aicspylibczi ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c3u1uy2c/aicspylibczi_28ac37e90f28422786d70db11f8a976d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c3u1uy2c/aicspylibczi_28ac37e90f28422786d70db11f8a976d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-crykfx2d/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/aicspylibczi
         cwd: /tmp/pip-install-c3u1uy2c/aicspylibczi_28ac37e90f28422786d70db11f8a976d/
    Complete output (59 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/aicspylibczi
    copying aicspylibczi/_version.py -> build/lib.linux-x86_64-3.6/aicspylibczi
    copying aicspylibczi/CziFile.py -> build/lib.linux-x86_64-3.6/aicspylibczi
    copying aicspylibczi/__init__.py -> build/lib.linux-x86_64-3.6/aicspylibczi
    copying aicspylibczi/types.py -> build/lib.linux-x86_64-3.6/aicspylibczi
    running egg_info
    writing aicspylibczi.egg-info/PKG-INFO
    writing dependency_links to aicspylibczi.egg-info/dependency_links.txt
    writing requirements to aicspylibczi.egg-info/requires.txt
    writing top-level names to aicspylibczi.egg-info/top_level.txt
    reading manifest file 'aicspylibczi.egg-info/SOURCES.txt'
    writing manifest file 'aicspylibczi.egg-info/SOURCES.txt'
    running build_ext
    CMake Error: The source directory "/tmp/pip-install-c3u1uy2c/aicspylibczi_28ac37e90f28422786d70db11f8a976d" does not appear to contain CMakeLists.txt.
    Specify --help for usage, or press the help button on the CMake GUI.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-c3u1uy2c/aicspylibczi_28ac37e90f28422786d70db11f8a976d/setup.py", line 128, in <module>
        zip_safe=False,
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-install-c3u1uy2c/aicspylibczi_28ac37e90f28422786d70db11f8a976d/setup.py", line 104, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-c3u1uy2c/aicspylibczi_28ac37e90f28422786d70db11f8a976d', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-c3u1uy2c/aicspylibczi_28ac37e90f28422786d70db11f8a976d/build/lib.linux-x86_64-3.6', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c3u1uy2c/aicspylibczi_28ac37e90f28422786d70db11f8a976d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c3u1uy2c/aicspylibczi_28ac37e90f28422786d70db11f8a976d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-crykfx2d/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/aicspylibczi Check the logs for full command output.

**Comment by JacksonMaxfield** [comment]
I think you need to install a prior version. 3.0.5 isn't built for Py36.

(This is on us / the previous maintainer... there is a lack of metadata in the package info. If the package metadata had a "Python Supports" section pip wouldn't have even attempted to install a version your system doesn't support. cc @toloudis seems we should add package metadata.)

You have two options, upgrade to Py37+ or install from an old version:
If you are going to install from an old version I would try: `pip install --force-reinstall aicspylibczi==3.0.1` as that was the last version I can tell supported Py36.

**Comment by NSGregory** [comment]
Installing version 3.0.1 worked for me in this case.  I don't know if you want to leave this open for others to find until the metadata gets addressed.  Thanks for the speedy reply.

**Comment by JacksonMaxfield** [comment]
Thanks for the update! I changed this issue to "Add package metadata to help pip install valid versions" -- I will track it / work on it hopefully soon.

**Comment by pgarrison** [comment]
FWIW, I ran into this today using python `3.11.0rc1` (but I installed just fine with python `3.10.6`)

**Comment by toloudis** [comment]
> FWIW, I ran into this today using python `3.11.0rc1` (but I installed just fine with python `3.10.6`)

#110 hopefully will start our support of python 3.11.

**Comment by toloudis** [comment]
@pgarrison aicspylibczi 3.1.1 should now have proper support for Python 3.11 installation.  Let's open new issues if anything is broken moving forward.
