### ISSUE TITLE
How to export to a TIFF or svs ？

### ISSUE THREAD

**Issue by shenxiaochenn** [AllenCellModeling/aicspylibczi#113]
In fact, is there a way to output czi to TIFF format or svs format？ That way, it can be opened in the openslide for further analysis. In daily use, I think maybe openslide is really good and convenient. Thanks!

**Comment by evamaxfield** [comment]
Hey @shenxiaochenn. This package is only for reading CZI files. However our related package [aicsimageio](https://github.com/AllenCellModeling/aicsimageio) uses this package to enable reading CZIs and then writing TIFFs with the same pixel data.

an example:

```python
from aicsimageio import AICSImage
from aicsimageio.writers import OmeTiffWriter

image = AICSImage("your-czi-file-path.czi")
OmeTiffWriter.save(
    image.data,
    "new-file.ome.tiff",
    dim_order=image.dims.order,
    channel_names=image.channel_names,
)
```
