### ISSUE TITLE
Build and publish wheels for python3.12

### ISSUE THREAD

**Issue by pe224** [AllenCellModeling/aicspylibczi#117]
@toloudis would it be possible to re-run the CI/CD build/publish script for the currently latest version?
Thanks!

**Comment by toloudis** [comment]
Thanks for adding this issue.  Currently our github-actions builds are broken because of github's change of macos-latest to use arm64. We will get to this next week at the soonest. (PRs always welcome of course!)

**Comment by pe224** [comment]
This seems to be fixed with release 3.2.0
Thanks!
