### ISSUE TITLE
Release Python 3.6 and 3.8 builds

### ISSUE THREAD

**Issue by JacksonMaxfield** [AllenCellModeling/aicspylibczi#31]
Only building on 3.7 is limiting

**Comment by heeler** [comment]
Addressed by release 2.5 - wheels for 3.6, 3.7, and 3.8 - should also support OSX10.13 through latest

**Comment by ExtReMLapin** [comment]
I could be missing something but there is no 3.8 build on [PyPI](https://pypi.org/project/pylibczi/#files)
