### ISSUE TITLE
Fix lint checks in GitHub actions

### ISSUE THREAD

**Issue by JacksonMaxfield** [AllenCellModeling/aicspylibczi#42]
Looks like someone copied some code :eyes: :upside_down_face: 

https://github.com/AllenCellModeling/aicspylibczi/blob/master/.github/workflows/pythonbuild.yml#L46

**Comment by heeler** [comment]
Sure did lol. I'm guessing I had the wrong project name in there but it is correct now. Thanks for pointing it out.
