### ISSUE TITLE
Wrong czi.dims order or misunderstanding (or wrong expectation) from my side

### ISSUE THREAD

**Issue by sebi06** [AllenCellModeling/aicspylibczi#45]
Hi,

I acquired a CZI called: WP96_2Pos_B2+B4_S=2_T=2_Z=4_C=3_X=512_Y=256.czi and used the following dimension order during acquistion:

![image](https://user-images.githubusercontent.com/3833249/92938483-e4b54c00-f44c-11ea-83fb-f94463be6170.png)

So my expectation is the the dimension string is like STZCYX. But when I use the following code:

```python
from aicspylibczi import CziFile

filename = r'testdata\WP96_2Pos_B2+B4_S=2_T=2_Z=4_C=3_X=512_Y=256.czi'
czi = CziFile(filename)

# Get the shape of the data, the coordinate pairs are (start index, size)
print(czi.dims_shape())
print(czi.dims)
print(czi.size)
print(czi.dims_shape())
print(czi.dims)
print(czi.size)
```
I get the following output:

```text
[{'X': (0, 512), 'Y': (0, 256), 'Z': (0, 4), 'C': (0, 3), 'T': (0, 2), 'S': (0, 2), 'H': (0, 1)}]
HSTCZYX
(1, 2, 2, 3, 4, 256, 512)
```

So it fits, but I was expecting C-Z switched:

```text
[{'X': (0, 512), 'Y': (0, 256), 'Z': (0, 4), 'C': (0, 3), 'T': (0, 2), 'S': (0, 2), 'H': (0, 1)}]
HSTZCYX
(1, 2, 2, 4, 3, 256, 512)
```

I supsect this is a wrong expectation from my side and dimension order has nothing todo with acquistion order, right?

The CZI is attached as a zip. Feel free to use for anything.
[WP96_2Pos_B2+B4_S=2_T=2_Z=4_C=3_X=512_Y=256.zip](https://github.com/AllenCellModeling/aicspylibczi/files/5209689/WP96_2Pos_B2%2BB4_S.2_T.2_Z.4_C.3_X.512_Y.256.zip)

**Comment by heeler** [comment]
Hi @sebi06, 
Thanks for pointing this out and for sharing the file. The default sort order baked into my code is 
```
  enum class DimIndex: std::uint8_t {
      invalid = 0,    ///< Invalid dimension index.

      MinDim = 1,        ///< This enum must be have the value of the lowest (valid) dimension index.

      X = 1,          ///< The X-dimension.  ** NOT in libCZI::DimensionIndex.
      Y = 2,          ///< The Y-dimension.  ** NOT in libCZI::DimensionIndex.
      Z = 3,            ///< The Z-dimension.
      C = 4,            ///< The C-dimension ("channel").
      T = 5,            ///< The T-dimension ("time").
      R = 6,            ///< The R-dimension ("rotation").
      M = 7,            ///< The m_index.    ** NOT in libCZI::DimensionIndex.
      S = 8,            ///< The S-dimension ("scene").
      I = 9,            ///< The I-dimension ("illumination").
      H = 10,            ///< The H-dimension ("phase").
      V = 11,            ///< The V-dimension ("view").
      B = 12,            ///< The B-dimension ("block") - its use is deprecated.

      MaxDim = 12    ///< The highest (valid) dimension index.
  };
```

If I'm thinking through the code correctly this essentially defines the default sort order for dimensions. 
For consistency, this is order is imposed on the data returned. From looking at the file after acquisition I don't think I'd be able to infer an order from the acquisition unless it's stored in the metadata block which I have generally avoided using based on the assumption that the binary image side of the file was more crucial/accurate. I will check to see if there is a mismatch between the array returned and the stated image ordering which I would need to address. 

Hopefully, my answer makes sense. If it doesn't or I'm misunderstanding something you've said please let me know.

**Comment by heeler** [comment]
I think this has been addressed but if not ping me or reopen the issue.
