### ISSUE TITLE
Mosaic scene_bounding_box returns incorrect width and height.

### ISSUE THREAD

**Issue by djdt** [AllenCellModeling/aicspylibczi#49]
On a mosaic image the scene bounding box width and height are set to the width and height of a single subblock rather than the entire scene.

It looks like the issue is in getSceneYXSize, it returns on the first subblock found for mosaic images.

I can work around this by iterating through every M_index and using read_subblock_rect to determine the min/max x/y returned but it is quite slow.

**Comment by heeler** [comment]
did you try the function `read_mosaic_size` ?
`read_mosaic_size` is meant to return the size of the mozaic image `scene_bounding_box` is for conventional images. 
With mosaic images, the Scene dimension doesn't have an easily interpretable meaning.

**Comment by djdt** [comment]
That gives the correct size for the entire image, but I am trying to load a single scene in a multi scene image.

The scene dimension seems to correctly specify the mosaic tiles that belong to the scene.
With the correct area I can read just the scene using read_mosaic.

**Comment by heeler** [comment]
So you have a Mosaic image and you want the bounding box (x, y, w, h) of all the subblocks with the same Scene index? Is that correct? 
I'll have a think if there's something easy I can expose that would give you what you want. 
From my understanding of mosaic files this will give you a contiguous region within the entire mozaic. 
I'll have a deeper look as soon as I get a chance.

**Comment by djdt** [comment]
That's correct.
I think the easiest way would be to either:
Collect all the mosaic tiles with the same scene index and finding the largest bounding box that contains them all.
Return a list of bounding boxes with a certain scene index.
Thanks!

**Comment by sebi06** [comment]
Any news on this since I have the exact same issue. I need to read a single scene from a multi-scene CZI image, where every scene has different dimensions. And some scenes are a mosaic, while other are not. I know this sounds quite like an edge case, but in reality I have seen this quite often.

So fro me a convenience function that give a complete scene from a multi-scene image incl. the scale would be perfect

**Comment by heeler** [comment]
So my thought is in the case of a mosaic file to return the complete list of bounding boxes matching specified dimensions and then the developer can decide how they want to use that. Would that work? In addition to the bounding box for each subblock, what metadata would you need/want to give context to the bounding boxes? 

I'm working on a PR right now. Once that is in I'll push this through as well and my hope is to have a new release version out sometime this week with the feature enabled.

**Comment by sebi06** [comment]
This would of course help. Nevertheless from a User perspective the goal is to read a specific scene as one image with a specific scale. I am not sure if that can be easily implemented, but it would be very helpful for sure.

Obviously this depends a bit from the perspective. For "real" developers your suggestion is probably good enough, but for people doing BioImage Analysis "on the scripting" level my suggestion might be more useful. What is your take on that?

**Comment by djdt** [comment]
As long as the returned subblocks are limited to those with where the scene is specified the bounding boxes would be all that is needed for my purposes. I would be easy to find the maximum extents of those, which could then be passed to read_mosaic to read at any scale.

**Comment by sebi06** [comment]
I agree. This would be already very helpful. Finding the maximum extend should not be too hard.

**Comment by heeler** [comment]
I'll finish this tomorrow and put it in for PR to be merged into the next release which will happen as soon as it's approved. Thanks for the suggestions.
