### ISSUE TITLE
MemoryError: std::bad_alloc for read_mosaic in versions > 2.6.0

### ISSUE THREAD

**Issue by djdt** [AllenCellModeling/aicspylibczi#57]
The read_mosaic function throws a 'MemoryError: std::bad_alloc' when called. This can be fixed by reverting to version 2.6.0.

**Comment by heeler** [comment]
I think I have traced this back to a bug in libCZI but I think I have a workaround. I hope to have a fix out for you tomorrow.

**Comment by heeler** [comment]
2.7.3 should be on pypi now. If you wouldn't mind giving that a try I'd really appreciate it. 
There is a subtle bug in libCZI but I haven't been able to rule out that it might be in my code that causes, a skew in the image for certain scale factors. I'll work on this but it will be a different PR. The segfault you were encountering should be addressed by 2.7.3. Thanks for reporting this. Cheers! 

PS: if you could comment here if it worked for your purposes that would be great.

**Comment by djdt** [comment]
It no longer segfaults but the image is corrupted in some way. The top image is 2.7.3 and the bottom with version 2.6.0.

![image](https://user-images.githubusercontent.com/10266332/98937616-c34f0a00-253a-11eb-9cde-e66379a6ab09.png)
![image](https://user-images.githubusercontent.com/10266332/98937778-027d5b00-253b-11eb-96ff-7c9b3e75a3d4.png)

**Comment by heeler** [comment]
That's the skew I mentioned. I'll work on that today. It seemed only to happen for certain scalefactors. IE: 1.0, 0.1, 0.2 might all work fine but 0.3, .... could be skewed. Thanks for the feedback I'll post here again when I have a fix together.

**Comment by heeler** [comment]
Hi @djdt, So I think this is now working. There's a new aicspylibczi 2.7.5 which works for all scalefactor <= 1.0 at least with the files I was able to test against. If you would please give the new version a try and let me know if it's performing satisfactorily for you. I really appreciate your posts! Thanks!

**Comment by djdt** [comment]
Hey, it works great now and is much faster than before! Thanks for all the work on this!

**Comment by JacksonMaxfield** [comment]
Great work @heeler!

**Comment by heeler** [comment]
Thanks @djdt! Thanks @JacksonMaxfield! Much appreciated.
