### ISSUE TITLE
Mosaic image size differs from mosaic dimentions

### ISSUE THREAD

**Issue by plankter** [AllenCellModeling/aicspylibczi#62]
All CZI files I tried show the difference between `read_mosaic_size` and final image size read via `read_mosaic`.

![image](https://user-images.githubusercontent.com/1336618/100327905-2c6b5e80-2fcc-11eb-804e-f63e1ec62628.png)

However, reading via `czi.read_mosaic(region=czi.read_mosaic_size(), C=0)` returns expected dimensions.

**Comment by heeler** [comment]
I'll look into this and get back to you. Thanks for pointing it out. Sorry for the delay in responding I was unplugged over the local holiday here.

**Comment by heeler** [comment]
@plankter what version number of aicspylibczi are you using? I've tested locally with 3 mosaic files with aicspylibczi 2.7.5 and so far haven't been able to reproduce the mismatch. If you are on an older version please update and let me know if the bug persists. If the bug persists is there any chance you could share the file? Thanks!

**Comment by heeler** [comment]
@plankter when you have time could you let me know if this is working for you with >=2.7.5? Thanks.

**Comment by dimi-huer** [comment]
### Coordinates Overspecified Exception with certain Mosaic files

I get an issue related to this topic, I discovered it when I tried opening a tilescan with _aicsimageio_.
So, I created a library with any type of possible combinations of dimensions: M, S, T and Z with two channels.

Versions of packages I was using:

python: 3.8.5
aicspylibczi: 2.7.6
aicsimageio: 3.3.3
czifile: 2019.7.2

If I try to open tilescans (all of them with two channels) with only tiles, tiles and time, tiles and z, or tiles, time and z I get an error in line 57 of the file aicspylibczi/CziFile.py: __aicspylibczi.PylibCZI_CDimCoordinatesOverspecifiedException_

However, if I have positions (S) as an additional dimension I don't get this error, but I do get the same behaviour as already specified in this issue and there:  [AllenCellModeling/aicsimageio/issues/163].

I tried using CziFile in terminal, but also from scripts, starting with AICSImage or CziReader. In contrary, if I use the package czifile everything works smoothly and I can load any of the files.

I can provide the file library I created via E-Mail.

**Comment by dimi-huer** [comment]
@heeler I do get the same as @plankter reported with my .czi files with >=2.75 (with the ones I could open, see: AllenCellModeling/aicspylibczi/issues/67)

However, if I use the file: AllenCellModeling/aicspylibczi/tests/resources/mosaic_test.czi it works.

Also width and height order are switched in between the two methods.

**Comment by heeler** [comment]
Can you share the file with me, jamies@alleninstitute.org. I will treat the file as confidential. If you could share it via dropbox or google drive or something similar that would be great and just directly email me the info I'll take a shot at it asap.

**Comment by dimi-huer** [comment]
I am sorry, but I believe I misunderstood something before.

Image size (width and height) is consistent, though width and height are swapped, between `read_mosaic_size()` and `read_mosaic()`, which might have caused some distraction to me.

Something new came up to me with scenes. Shouldn't it be possible to choose a scene in `read_mosaic(C=0, S=0)`?
If I try it, I get a _DimCoordinatesOverspecifiedException_. Is S already chosen?

Sorry for the misinterpretation from my side.

**Comment by heeler** [comment]
Hi @dimi-huer, 

On the question of `read_mosaic(C=0, S=0)` I apologize I should have documented that S is an invalid constraint, so it would have to be `read_mosaic(C=0)` to work and it would be the entire mosaic image. The way Zeiss has implemented mosaic images they to some extent abstract away the concept of a scene and instead introduce `m_index` which has the property that an image with the same m_index describes the same region. The workaround for this is to figure out the (x0, y0, w, h) region of the image that S=0 is captured in and to specify this with the region command. It's not ideal but the libCZI API forces my hand on this. 

On the issue of width heigh being swapped it could very well be and I'm sorry about the confusion. I'm about to start on a 3.0 API overhaul and I will unify these to be more consistent. Some of these functions were written for non-mosaic files and some for mosaic files. With the 3.0 release, this will hopefully be unified to be consistent and more interpretable. 

So am I correct in thinking that the code itself works ok but how to call the functions is confusing and could be improved?

Thanks for taking the time to post an issue and any suggestions are more than welcome.

**Comment by dimi-huer** [comment]
Hi @heeler 

Okay, I thought so, because that was working for me. Would it then be an option to make 'M' a subdimension of the m_index, which is the 'S' dimension, like giving it more attributes if a file is mosaic type? Could it be possible that this is already the case somehow and this is why my mosaic files without a 'S' dimension fail to open? (#67 ) 

Thank you for clarifying the code, it helps to understand more of it.
Looking forward to this update.

On the files I can load it works, yes.

Thank you.

**Comment by heeler** [comment]
Hi @dimi-huer, So I went through the files you shared and was able to determine the following:

Mosaic files:
pos_tiles_time.czi
pos_tiles_time_z.czi
pos_tiles_z.czi
pos_tiles.czi

Normal CZI Files (NOT MOSAICS):
pos_time.czi
pos_time_z.czi
pos_z.czi
pos.czi
time_z.czi
time.czi
z.czi

Problem Files:
tiles_time_z.czi: 
    Mosaic: True 
    Dims: BVTCZMYX
    Shape: [{'X': (0, 256), 'Y': (0, 256), 'Z': (0, 2), 'C': (0, 2), 'T': (0, 2), 'M': (0, 4), 'V': (0, 1), 'B': (0, 1)}]

tiles_z.czi: 
    Mosaic: True 
    Dims: BVTCZMYX
    Shape: [{'X': (0, 256), 'Y': (0, 256), 'Z': (0, 2), 'C': (0, 2), 'T': (0, 1), 'M': (0, 4), 'V': (0, 1), 'B': (0, 1)}]

tiles.czi: 
    Mosaic: True 
    Dims: BVTCZMYX
    Shape: [{'X': (0, 256), 'Y': (0, 256), 'Z': (0, 1), 'C': (0, 2), 'T': (0, 1), 'M': (0, 4), 'V': (0, 1), 'B': (0, 1)}]

For the "Problem Files" I modified a version not to require a scene for mosaic files but I'm not sure what values to expect. I was surprised to see the V in the dimensions but I have seen that before. Do the dimensions match what you expect? 
If this makes sense I'll build a new release with the patch. Thank you for sharing the files, it exposed an edge case that I hadn't considered.

**Comment by dimi-huer** [comment]
Hi @heeler 

Thank you a lot for solving it so quickly. I believe also the tiles_time.czi was a problem file?
I don't fully understand the B and the V dimensions. Is the B dimension coming from multiple experiments, if the experiment designer is used? All the other dimensions match what I would expect.

Great that I could help solving this issue.

**Comment by heeler** [comment]
I believe this is resolved now. If something is still outstanding that I missed please reopen the issue and draw my attention to it. Thanks!
