### ISSUE TITLE
Reading parts of a CZI using BoundingBox derived from czi.mosaic_scene_bounding_boxes

### ISSUE THREAD

**Issue by sebi06** [AllenCellModeling/aicspylibczi#65]
Hi,

i use pyaicslibczi = 2.7.5 and cannot warp my head around the following problem (might be my mistake).

I have a CZI with 2 equal scenes (width = 2944, height = 3444 for each scene)

![image](https://user-images.githubusercontent.com/3833249/102183578-59fe4600-3eae-11eb-902b-b89657caadae.png)

I use the following code

```python
# read CZI using aicslibczi
czi = CziFile(filename)
print('Mosaic Size: ', czi.read_mosaic_size())

# read sizes for all scenes
for s in range(2):

    # get the bounding boxes
    bboxes = czi.mosaic_scene_bounding_boxes(index=s)
    xmin = min(bboxes[:])[0]
    ymin = min(bboxes[:])[1]
    xmax = max(bboxes[:])[0] + max(bboxes[:])[2]
    ymax = max(bboxes[:])[1] + max(bboxes[:])[3]

    # read the specific part of the CZI
    region = czi.read_mosaic(region=(xmin, ymin, xmax, ymax),
                             scale_factor=1.0,
                             C=0)
    print('BBox Scene: ', s, region.shape)
```

It seems to work fine for the 1st scene but when trying to read the 2nd scene I get:

```text
Mosaic Size:  (0, 0, 47944, 3444)
BBox Scene:  0 (1, 3444, 2944)
Traceback (most recent call last):
  File "c:/Users/m1srh/Documents/GitHub/czi_demos/test_bboxes_czi.py", line 29, in <module>
    C=0)
  File "C:\ProgramData\Anaconda3\envs\imageanalysis\lib\site-packages\aicspylibczi\CziFile.py", line 458, in read_mosaic
    img = self.reader.read_mosaic(plane_constraints, scale_factor, region)
_aicspylibczi.PylibCZI_RegionSelectionException: Requirement violated requested region is not a subset of the defined image!
         (45000,0,47944,3444) ⊄ (0,0,47944,3444)
        Requested region not in image!
```

What do I miss here? Did I mix up X and Y or is there a -1 to be added somewhere, e.g. the array goes from 0-2943 etc.? Any help is really appreciated.

**Comment by heeler** [comment]
Hi @sebi06! My guess off the top of my head is that the format it is expecting (x0, y0, w, h) so if x0 is 45000 then w has to be at most 47944 - 45000. I think your assuming (xStart, yStart, xEnd, yEnd). 

The input region is defined as:
region – A rectangle specifying the extraction box (x, y, width, height) specified in pixels

If that doesn't fix your problem and if you can share the file with me and I'll try digging into it in the morning.

**Comment by sebi06** [comment]
Ok, I will try. But the 2nd scene XStart is exactly at 45000 pixels if you consider the whole image including both scenes. The CZI can be downloaded here:

https://drive.google.com/file/d/1p-XuEHnrl6MyyNDZpGbRrpFzvXfSenQI/view?usp=sharing

**Comment by heeler** [comment]
The start is correct the width is what's causing you a problem I believe. 
My best guess is that region should be 
(45000, 0, 2944, 3444)
Let me know if that works for you if you would.

**Comment by sebi06** [comment]
In ZEN i have:

![image](https://user-images.githubusercontent.com/3833249/102195293-ae112680-3ebe-11eb-9759-0be02eb5bdeb.png)

Let me check again.

**Comment by sebi06** [comment]
So the correct code snippet then would be:

```python
# read sizes for all scenes
for s in range(md['SizeS']):

    # get the bounding boxes
    bboxes = czi.mosaic_scene_bounding_boxes(index=s)
    xmin = min(bboxes[:])[0]
    ymin = min(bboxes[:])[1]
    width = max(bboxes[:])[0] + max(bboxes[:])[2] - xmin
    height = max(bboxes[:])[1] + max(bboxes[:])[3] - ymin

    # read the specific part of the CZI
    region = czi.read_mosaic(region=(xmin, ymin, width, height), scale_factor=1.0, C=0)
    print('BBox Scene: ', s, region.shape)
```

Make sense now that I look at it.

**Comment by sebi06** [comment]
I tied this with a more "fancy" CZI at then the approach fails directly for the first file. 

![image](https://user-images.githubusercontent.com/3833249/102208487-c76e9e80-3ecf-11eb-8532-42b92ba4e0c2.png)

https://drive.google.com/file/d/16SPi6V2R4TTu0wjx8f5isHE4syttSboj/view?usp=sharing

**Comment by sebi06** [comment]
I found at least one mistake .... - my code. I modified it (see below) and now it also works with the file from above. feel free to keep those CZI for your purposes. I am still not sure if that code is the best approach to read scenes from an CZI scene-by-scene.

```python
# read CZI using aicslibczi
czi = CziFile(filename)
size = czi.read_mosaic_size()
print('Mosaic Size: ', size)

# read sizes for all scenes
for s in range(md['SizeS']):

    # get the bounding boxes for the current scene
    bboxes = czi.mosaic_scene_bounding_boxes(index=s)
    xstart = []
    ystart = []
    tilewidth = []
    tileheight = []

    for b in range(len(bboxes)):

        box = bboxes[b]
        # get all xmin values
        xstart.append(box[0])
        ystart.append(box[1])
        tilewidth.append(box[2])
        tileheight.append(box[3])

    XMIN = min(xstart)
    YMIN = min(ystart)
    WIDTH = max(xstart) - XMIN + tilewidth[-1]
    HEIGHT = max(ystart) - YMIN + tileheight[-1]

    # read the specific part of the CZI
    region = czi.read_mosaic(region=(XMIN, YMIN, WIDTH, HEIGHT), scale_factor=1.0, C=0)
```

**Comment by sebi06** [comment]
It did some more test and it seems to work now. Just the naming of the function is misleading. I will open a separate issue for this.
