### ISSUE TITLE
ERROR: no matching distribution found for aicspylibczi

### ISSUE THREAD

**Issue by bryantChhun** [AllenCellModeling/aicspylibczi#68]
I'm receiving this error on any 2.7 release while installing as a dependency (or individually) from aicsimageio

This looks exactly the same as an issue from january 2020, except this time with the 2.7 release: #28 

```
ERROR: Could not find a version that satisfies the requirement aicspylibczi~=2.7.5 (from aicsimageio)
ERROR: No matching distribution found for aicspylibczi~=2.7.5
```

similar env as the user earlier:

```
            shell level : 1
       user config file : /Users/bryant.chhun/.condarc
 populated config files : /Users/bryant.chhun/.condarc
          conda version : 4.8.5
    conda-build version : 3.10.5
         python version : 3.6.11.final.0
       virtual packages : __osx=10.13.6
       base environment : /Users/bryant.chhun/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/talley/osx-64
                          https://conda.anaconda.org/talley/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
               platform : osx-64
             user-agent : conda/4.8.5 requests/2.22.0 CPython/3.6.11 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

```
python 3.7.9
pip 20.3.1
```

**Comment by heeler** [comment]
Hi @bryantChhun, umm first off it looks like your actually on python 3.6 not 3.7 from your environment output but that shouldn't be a big deal. I would recommend using 3.7 or later generally. Given the output, I'm assuming you're on macOS? 

We use pip for installs and don't directly publish a conda package. 
Try `pip install aicspylibczi` after activating your conda environment and it should work. 
If for some reason it doesn't please respond here and I'll try to get back to you right away.

**Comment by bryantChhun** [comment]
@heeler Thanks for the response.  `pip install aicspylibczi` works but defaults to version 2.6.  I noticed the problem when installing `aicsimageio`, which specifies `aicspylibczi >= 2.7.5` as a dependency.

If i try installing 2.7.6 as here https://pypi.org/project/aicspylibczi/2.7.6/, i will get the above error

**Comment by heeler** [comment]
I'm having a really hard time reproducing your issue. 

can you check to make sure there isn't a pip.conf somewhere that's having impact here? 
```
Per-user:

On Unix the default configuration file is: $HOME/.config/pip/pip.conf which respects the XDG_CONFIG_HOME environment variable.

On macOS the configuration file is $HOME/Library/Application Support/pip/pip.conf if directory $HOME/Library/Application Support/pip exists else $HOME/.config/pip/pip.conf.
There is also a legacy per-user configuration file which is also respected. To find its location:

On Unix and macOS the configuration file is: $HOME/.pip/pip.conf
```

Also so we're on the same page could you try this series of commands 
```
conda create -n testThis python=3.7
conda activate testThis
pip install aicsimageio
``` 
If this doesn't work please post the output back here. 

On every attempt I make it installs aicspylibczi=2.7.6 cleanly.

**Comment by bryantChhun** [comment]
I can install aicsimageio using the above commands, and even used `--no-cache-dir` to make sure it's fresh.  It still defaults to 2.6 (and aicsimageio will default to 3.3.1, which has an older dependency)

![image](https://user-images.githubusercontent.com/25647712/104057941-cca9cb00-51a7-11eb-9211-9f4c81b74ac8.png)

If i try to install 3.3.3, I get the same error:

![image](https://user-images.githubusercontent.com/25647712/104059412-27442680-51aa-11eb-8074-c5cd222b0ff3.png)

Additionally, I can not find any pip.conf anywhere in the paths you listed above.

Could this be a mac OS version issue?

**Comment by heeler** [comment]
It's possible it could be an OS version issue but my build file contains the following statement
```
    IF (APPLE)
        set(CMAKE_OSX_DEPLOYMENT_TARGET "10.13" CACHE STRING "Minimum OS X deployment version" FORCE)
    ENDIF(APPLE)
```
Which I believe sets 10.13 as the minimum supported version. 


Let's try forcing the version for aicspylibczi and then if it works installing aicsimageio
```
conda activate testThis
pip install aicspylibczi==2.7.6
pip install aicsimageio
```

**Comment by heeler** [comment]
One other thought i had was to download the whl file from [pypi](https://files.pythonhosted.org/packages/54/e4/39ee16166619b71968c171f47ef4a7aca596138c7612d9d2d203acae5ba6/aicspylibczi-2.7.6-cp37-cp37m-macosx_10_14_x86_64.whl) so it's local to your system then 
```
pip install path/to/aicspylibczi-2.7.6-cp37-cp37m-macosx_10_14_x86_64.whl 
``` 

If it doesn't install I'd be very curious to know what message it gives.

**Comment by bryantChhun** [comment]
Ah thank you!  I hope this was more helpful than painful.  In the meantime I am more encouraged to upgrade my OS :-)

**Comment by JacksonMaxfield** [comment]
@heeler We may want to build aicspylibczi on more platforms

https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources

`macos-11.0` and `macos-10.15` / `macos-latest` are different.

**Comment by heeler** [comment]
@JacksonMaxfield This is what throws me though. Generally for building binaries (the C++ target) the compiler flags/libraries you link against (target) sets the minimal macOS version. In C++ build instructions, we explicitly say 10.13. Somewhere along the way, it's now targeting 10.14 in the wheel that gets built. 

To your main point, I have no issue with expanding the build matrix. I'm just not 100% sure where the constraint is. The current version is built on 10.15 but the wheel is compatible with 10.14 or 10.15 just not 10.13. 🤷

**Comment by JacksonMaxfield** [comment]
Oh yea. My comment wasn't so much about the current 10.13 issue but rather the general "I don't think we are building on 11.0" yet issue.

**Comment by heeler** [comment]
@bryantChhun So I got it to build for MacOS 10.9 forward. Unfortunately, the python binaries in the GH actions were build with 10.14 as the minimum supported MacOS. I used miniconda to install their binaries and then built against those and was thus able to get 10.9 onward support. Hopefully this works for you.
