### ISSUE TITLE
Displaying an RGB Image

### ISSUE THREAD

**Issue by MosGeo** [AllenCellModeling/aicspylibczi#71]
## System and Software
* aicspylibczi Version: 2.7.7
* Python Version: 3.8
* Operating System: Windows 10, 64 Bit

## Description
aicspylibczi recognizes the shape of the RGB file correctly but when loading the image and displaying it, it is not correct. It does not match the image displayed in Zen Blue.

## Expected Behavior
Correct display of the RGB image.

## Reproduction
As an example, I am using a test image included in this repository.

```
fileName = "RGB-8bit.czi"
czi = CziFile(fileName)
img, shp = czi.read_image()
img = np.squeeze(img)
img = np.moveaxis(img, [0, 1, 2], [2, 0, 1])

plt.figure(figsize=(20,10))
plt.subplot(1,3,1)
plt.imshow(img[:,:,0])
plt.subplot(1,3,2)
plt.imshow(img[:,:,1])
plt.subplot(1,3,3)
plt.imshow(img[:,:,2])

plt.figure(figsize=(20,10))
plt.imshow(img)
```

## Environment
Minimal Virtual environment with venv command (numpy, matplotlib, aicspylibczi, and their sub-requirements)

**Comment by MosGeo** [comment]
@heeler Thanks for the prompt response back in April 2020. Sorry about not following up as I got sidetracked by other projects that does not involve CZI files so I had to drop it. Anyway, I am probably doing something wrong with the above code but I can't seem to find it.

p.s. I am also looking into a possible issue with loading an RGB mosaic file.  It seems that reading one mosaic tile results in "3 channels" from different adjacent tiles rather than providing the three channels. I will update you once I do more tests.

**Comment by heeler** [comment]
Thanks for bringing this up. Is there a chance you could share the image from Zen Blue?

**Comment by MosGeo** [comment]
Below is the image as viewed in Zen Blue with the info detected in the software. Although the image looks green, it is not a false color. You will note that it says 24 Bit as expected of an RGB and it has the three channels. 

![RGB-8bit](https://user-images.githubusercontent.com/10503349/104887892-11d6b580-597d-11eb-971b-9b4dd6ca130a.jpg)

![Info](https://user-images.githubusercontent.com/10503349/104887978-2f0b8400-597d-11eb-9c0d-8722db17c1dd.png)

![Info2](https://user-images.githubusercontent.com/10503349/104888366-b3f69d80-597d-11eb-9a6a-3cf4df300b57.png)

**Comment by heeler** [comment]
Thanks. It's late here so I'll try and dig into this tomorrow.

**Comment by MosGeo** [comment]
No problem.  Cheers!

**Comment by heeler** [comment]
Thank you for posting this. Unfortunately when the memory optimization happened BRG (RGB) images ended up as an edge case that I test the shape but the condition to trigger the BRG24 -> gray8 wasn't being triggered. I'll get a patch out asap. It will likely be v2.8

**Comment by MosGeo** [comment]
I tested the fix with both 1 channel and multi-channel RGB images and it is working as expected. Great job! Thanks! I will test it on a  mosiac RGB tomorrow as I don't have access to one currently. But for the current issue, it is fixed and you can close the issue.

**Comment by heeler** [comment]
Thanks @MosGeo! When the PR fixing this is merged into master the issue will autoclose. Thanks again for sanity checking the fix!
