### ISSUE TITLE
Use of keyword "use_pylibczi" for the CZI file object

### ISSUE THREAD

**Issue by sebi06** [AllenCellModeling/aicspylibczi#73]
I tried to use the keyword **use_pylibczi** like described inside the source code. But it seems to me this is not used anymore because it throws an : `TypeError: __init__() got an unexpected keyword argument 'use_pylibczi'`

```text
"""Zeiss CZI file object.

    Args:
      |  czi_filename (str): Filename of czifile to access.

    Kwargs:
      |  metafile_out (str): Filename of xml file to optionally export czi meta data to.
      |  use_pylibczi (bool): Set to false to use Christoph Gohlke's czifile reader instead of libCZI.
      |  verbose (bool): Print information and times during czi file access."""
"""
```

**Comment by heeler** [comment]
Hi @sebi06, yes you are totally right. When I was developing the initial versions I had that option enabled but at some point when I trimmed dependencies and removed it I forgot to fix the docstring. 

What was the functionality that drove you there or was this something you just realized looking at the code?
Thanks for pointing it out. Next PR I'll check my docstrings and clean this up. 🙏

**Comment by sebi06** [comment]
I just saw it and was wondering... No worries.
