### ISSUE TITLE
Corrupted few columns of CZI file with 4.0.0

### ISSUE THREAD

**Issue by boazmohar** [AllenCellModeling/aicspylibczi#84]
## System and Software
* aicsimageio Version: 4.0.0
* Python Version: 3.8.10
* Operating System: linux [Oracle Linux Server release 8.3]

## Description
Corrupted few columns of czi data.

## Expected Behavior
Loading it with CziFile or native software shows there is no corruption in the raw data

## Reproduction
```python 
import aicsimageio
print(aicsimageio.__version__)
>>4.0.0
from aicsimageio import AICSImage
img = AICSImage('/nrs/svoboda/moharb/ExM/20210606_B6_IHC1/IHC1/IHC1.czi', chunk_by_dims=['CZ'])
print(img.shape)
>>(1, 4, 2170, 1920, 1920)
dask_array = img.dask_data
```
![image](https://user-images.githubusercontent.com/9434009/121234206-75487d80-c861-11eb-937e-ed9a8d1e5150.png)

```python 
plt.imshow(xarray[0,0,1,:,:], vmax=1000)
```
![image](https://user-images.githubusercontent.com/9434009/121234908-3a931500-c862-11eb-8eb6-9a389bb47a84.png)

## Environment
 aicspylibczi-3.0.1

I can upload the file to dropbox but it is 64Gb (lmk).
Thanks!

**Comment by toloudis** [comment]
I'm starting to take a look today. Will see how far I get.

**Comment by toloudis** [comment]
Here are my findings after digging into aicspylibczi and libCZI for a day.   I'm using the smaller Overview.czi file to test.

* the image loads correctly with czifile, and it also loads correctly in Zen
* open source libCZI (as compiled into aicspylibczi) appears to load the pixel data with a bad file offset, and so the data is shifted in the way shown in the pictures above
* I observed the same problem on both Mac and Windows.  The error seems to clearly have to do with file offsets where the data is being read
* I have a one line change in libCZI that seems to fix this image, but I have a feeling it may not be robust against ALL cases and would need to be reviewed by someone at Zeiss who knows that library 

One question I would have is: how was the image generated?  Are we seeing an image literally as it came off the microscope and/or has it been edited in any way?  I'm not sure if the inconsistent offsets I see in the file data are allowed and reasonable, or if there is some other bug happening way upstream of all this.

@sebi06 I wonder if you might have some insight into this.

**Comment by boazmohar** [comment]
@toloudis Thank for looking into this!
I can only add as to the generation of the data which is right off the microscope (Zeiss Z1 lightsheet). No edits were made.
If there is a complied version of this change that I can pull, I can test it with other files I generated off the same microscope.

**Comment by sebi06** [comment]
I need to point out that LightSheet Z1 is still running the old ZEN Black SW.
I would not create any big changes bases on such CZI image files.

Ideally they work as well but I would rather only test against CZI from ZEN Blue.

The overview.czi was acquired by me a while ago, but I cannot rember anymore, if I did some postprocessing like stitching etc.

But I can provide fresh CZI (using the latest software version) at any time. Those should be the reference.

What would you need?

**Comment by ptahmose** [comment]
The PR https://github.com/ptahmose/libCZI/pull/1 should fix the issue discussed here.
Note that the fix is applied to this repository (in the branch 'wolframlink') only at this point in time.
Hope this fixes the problem, and thanks for the analysis.

**Comment by toloudis** [comment]
@ptahmose @pthamose Thank you for this fast fix! We have a compile error because of mismatched types in the call to `max` which I patched like this: 
https://github.com/AllenCellModeling/libCZI/commit/2a8fdeb2f38d4bfae287b3987883118ab2b05938

**Comment by JacksonMaxfield** [comment]
This was marked as resolved but will not be actually fixed until we push a new version. Which will be shortly!

**Comment by JacksonMaxfield** [comment]
This should now be resolved. Can upgrade and use with `pip install --upgrade` or `pip install aicspylibczi==3.0.2`
