### ISSUE TITLE
Major Update of libCZI will take place soon

### ISSUE THREAD

**Issue by sebi06** [AllenCellModeling/aicspylibczi#88]
Hi all,

since aicspylibCZI is based on our **[libCZI](https://github.com/zeiss-microscopy/libCZI)** I think I might be a good idea to let you know that very soon (within the next weeks) we will release a major update for that library.

On main new feature will be the **[ZSTD compression](https://facebook.github.io/zstd/)** that is now implemented. In will be used in ZEN to write CZI files (optional).

I hope that that will then check aicspylibczi and build it on-top of this new version.

Cheers,

sebi06

**Comment by zeissmicroscopy** [comment]
The update version of libCZI with zstd support is now available on GitHub. See: [https://github.com/zeiss-microscopy/libCZI/pull/55](https://github.com/zeiss-microscopy/libCZI/pull/55) for details.

**Comment by JacksonMaxfield** [comment]
Thanks for the info!

With 1,148 files changed it's hard to tell what all has changed.

1. Are there breaking API changes? (This will affect if we need to change our code or if we can simply upgrade the submodule)
2. I _think_ I see that @heeler's and other's PRs were in some way merged in. Do we need to update our own fork or did all PRs of our own + community make it in to this official release? (If we need to update our own fork, this will take more time to get this build out)

Congrats on the release.

**Comment by JacksonMaxfield** [comment]
Bump @sebi06

**Comment by JacksonMaxfield** [comment]
@sebi06 bump again. Please.

**Comment by sebi06** [comment]
Hi @JacksonMaxfield

I am just back from vacation so sorry for the delayed answer.

AFAIK there are no breaking changes.

I think most of them were merged but I would have to ask the dev guys.

But since the ZSTD support is new I think I would make sence to start with a fresh fork of our updated repo.

What do you think?

**Comment by JacksonMaxfield** [comment]
Can you check with the devs please. Would appreciate the rundown.

**Comment by sebi06** [comment]
Hi @JacksonMaxfield 

i talked to the devs and the admitted, that that did not make a good job in "keeping" track of the PRs.
But they told me that to their knowledge there are no breaking changes.

I will clarify if I get "some time" to check you PRs from the past and hopefully merge them. Give me a few days .... :-)
